# Generated by Django 3.2.4 on 2021-06-11 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='地號')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='posts.post')),
            ],
        ),
    ]
